name: test-solazio 
version: 0.0.1
summary: A brand new testing snap
description: >
  Just a test python snap

confinement: strict
base: core18

architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: arm64

parts:
  test-solazio:
    plugin: python
    python-version: python3
    source: .

apps:
  test-solazio:
    command: python3 test_snap.py
