name: together-we-win
version: 0.0.3
summary: This is a nice test snap
description: >
  Just a test python snap

confinement: strict
base: core18

parts:
  together-we-win:
    plugin: python
    python-version: python3
    source: .

apps:
  together-we-win:
    command: python3 test_snap.py
